import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { test } from 'node:test'

const messageBubble = readFileSync('src/components/chat/MessageBubble.vue', 'utf8')
const fileTreePanel = readFileSync('src/components/filetree/FileTreePanel.vue', 'utf8')
const messageReferences = readFileSync('src/components/chat/MessageReferences.vue', 'utf8')
const chatPanel = readFileSync('src/components/chat/ChatPanel.vue', 'utf8')
const messageToolSummary = readFileSync('src/components/chat/MessageToolSummary.vue', 'utf8')
const skillPickerBar = readFileSync('src/components/chat/SkillPickerBar.vue', 'utf8')
const openCodePartList = readFileSync('src/components/chat/OpenCodePartList.vue', 'utf8')
const permissionDock = readFileSync('src/components/chat/PermissionDock.vue', 'utf8')
const questionDock = readFileSync('src/components/chat/QuestionDock.vue', 'utf8')
const todoDock = readFileSync('src/components/chat/TodoDock.vue', 'utf8')
const revertDock = readFileSync('src/components/chat/RevertDock.vue', 'utf8')
const followupDock = readFileSync('src/components/chat/FollowupDock.vue', 'utf8')
const diffReviewDock = readFileSync('src/components/chat/DiffReviewDock.vue', 'utf8')
const diffReviewSource = readFileSync('src/opencodeClient/diffReview.ts', 'utf8')
const sessionShareNotice = readFileSync('src/components/chat/SessionShareNotice.vue', 'utf8')
const agentStatusBar = readFileSync('src/components/chat/AgentStatusBar.vue', 'utf8')
const chatScrollNav = readFileSync('src/components/chat/ChatScrollNav.vue', 'utf8')
const toolPickerBar = readFileSync('src/components/chat/ToolPickerBar.vue', 'utf8')
const toolWarehousePanel = readFileSync('src/components/tools/ToolWarehousePanel.vue', 'utf8')
const workspaceLayout = readFileSync('src/layouts/WorkspaceLayout.vue', 'utf8')
const editorPanel = readFileSync('src/components/editor/EditorPanel.vue', 'utf8')
const i18nIndex = readFileSync('src/i18n/index.ts', 'utf8')
const useChat = readFileSync('src/composables/useChat.ts', 'utf8')
const agentStoreSource = readFileSync('src/stores/agentStore.ts', 'utf8')
const timelineRows = readFileSync('src/opencodeClient/timelineRows.ts', 'utf8')
const interactiveBridge = readFileSync('src/opencodeClient/interactive.ts', 'utf8')
const openCodeCatalog = readFileSync('src/opencodeClient/catalog.ts', 'utf8')
const toolConnectionAdapter = readFileSync('src/runtime/connection/toolConnectionAdapter.ts', 'utf8')
const markdownDisplayPolicy = readFileSync('src/components/chat/display/markdownDisplayPolicy.ts', 'utf8')
const tauriDefaultCapability = JSON.parse(readFileSync('src-tauri/capabilities/default.json', 'utf8'))
const composerCommandSource = chatPanel.slice(
  chatPanel.indexOf('const baseComposerCommands'),
  chatPanel.indexOf('const inputText = ref'),
)

test('chat messages use layout instead of visible user identity chrome', () => {
  assert.match(messageBubble, /v-if="showMeta"/)
  assert.doesNotMatch(messageBubble, /role === 'user' \? '你'/)
  assert.doesNotMatch(messageBubble, /role === 'user' \? 'person'/)
})

test('message action rows stay visible and use hover only for emphasis', () => {
  const actionRowBlock = messageBubble.match(/\.msg-action-row\s*\{[\s\S]*?\n\}/)?.[0] || ''
  assert.match(actionRowBlock, /opacity:\s*\.72;/)
  assert.doesNotMatch(actionRowBlock, /opacity:\s*0;/)
  assert.match(messageBubble, /\.msg:hover\s+\.msg-action-row/)
  assert.match(messageBubble, /\.msg:focus-within\s+\.msg-action-row/)
  const parentActionRowBlock = chatPanel.match(/\.msg-action-row\s*\{[\s\S]*?\n\}/)?.[0] || ''
  assert.match(parentActionRowBlock, /opacity:\s*\.72;/)
  assert.doesNotMatch(parentActionRowBlock, /opacity:\s*0;/)
})

test('message display uses the unified display model and text warning component', () => {
  assert.match(messageBubble, /buildMessageDisplayModel/)
  assert.match(messageBubble, /MessageTextWarning/)
  assert.match(messageBubble, /layout-\$\{displayModel\.value\.layout\}/)
})

test('search references are collapsed instead of leading the reading flow', () => {
  assert.match(messageBubble, /MessageReferences/)
  assert.match(messageReferences, /<details v-if="showSearchReferences" class="msg-search-refs">/)
  assert.match(messageReferences, /<summary class="msg-search-refs-title">搜索引用/)
  assert.doesNotMatch(messageReferences, /showKnowledgeReferences/)
  assert.doesNotMatch(messageReferences, /msg-knowledge-refs/)
  assert.ok(
    messageBubble.indexOf('<MessageReferences')
      > messageBubble.indexOf('class="msg-body"'),
    'references should render after the answer body',
  )
})

test('assistant prose layout makes long answers read like documents instead of heavy cards', () => {
  assert.match(messageBubble, /\.msg\.layout-assistant-prose\s+\.msg-bubble\s*\{[\s\S]*max-width:\s*820px;/)
  assert.match(messageBubble, /\.msg\.layout-assistant-prose\s+\.msg-bubble\s*\{[\s\S]*background:\s*transparent;/)
  assert.match(messageBubble, /\.msg\.layout-assistant-prose\s+\.msg-bubble\s*\{[\s\S]*line-height:\s*1\.76;/)
  assert.match(messageBubble, /\.msg\.layout-assistant-prose\s+:deep\(\.msg-body p\)\s*\{[\s\S]*margin:\s*0 0 \.78em;/)
  assert.match(messageBubble, /\.msg\.layout-assistant-prose\s+:deep\(\.msg-body h2\)\s*\{[\s\S]*margin-top:\s*1\.35em;/)
  assert.match(messageBubble, /\.msg\.layout-assistant-prose\s+:deep\(\.msg-body li\)\s*\{[\s\S]*margin:\s*\.28em 0;/)
})

test('code blocks and tables are contained like professional answer artifacts', () => {
  assert.match(messageBubble, /renderMessageMarkdown/)
  assert.match(markdownDisplayPolicy, /class="md-table-wrap"/)
  assert.match(markdownDisplayPolicy, /aria-label="复制代码"/)
  assert.match(markdownDisplayPolicy, /<span class="mso" aria-hidden="true">content_copy<\/span>/)
  assert.match(messageBubble, /:deep\(\.md-code\)\s*\{[\s\S]*max-width:\s*100%;/)
  assert.match(messageBubble, /:deep\(\.md-code pre\)\s*\{[\s\S]*overflow-x:\s*auto;/)
  assert.match(messageBubble, /:deep\(\.md-table-wrap\)\s*\{[\s\S]*overflow-x:\s*auto;/)
  assert.match(messageBubble, /:deep\(\.md-table-wrap table\)\s*\{[\s\S]*min-width:\s*520px;/)
  assert.match(messageBubble, /:deep\(\.md-table-wrap td\)\s*\{[\s\S]*max-width:\s*320px;/)
})

test('message copy actions prefer native desktop clipboard before WebView fallbacks', () => {
  assert.match(messageBubble, /async function writeClipboardText\(/)
  assert.match(messageBubble, /isTauriRuntime\(\)/)
  assert.match(messageBubble, /invoke\('write_clipboard_text'/)
  assert.match(messageBubble, /navigator\.clipboard\?\.writeText/)
  assert.match(messageBubble, /document\.execCommand\('copy'\)/)
  assert.match(messageBubble, /let text = normalizedContent\.value/)
  assert.match(messageBubble, /await writeClipboardText\(text\)/)
  assert.match(messageBubble, /await writeClipboardText\(code\)/)
})

test('desktop app exposes a native clipboard command for reliable copy', () => {
  const tauriLib = readFileSync('src-tauri/src/lib.rs', 'utf8')
  assert.match(tauriLib, /fn write_clipboard_text\(/)
  assert.match(tauriLib, /Stdio::piped\(\)/)
  assert.match(tauriLib, /pbcopy/)
  assert.match(tauriLib, /write_clipboard_text,/)
})

test('tool calls render as a quiet summary with folded details and file rows', () => {
  assert.match(messageBubble, /MessageToolSummary/)
  assert.doesNotMatch(messageBubble, /ToolCallCard/)
  assert.match(messageToolSummary, /class="tool-summary"/)
  assert.match(messageToolSummary, /aria-expanded="showDetails"/)
  assert.match(messageToolSummary, /v-if="showDetails && toolCalls && toolCalls\.length"/)
  assert.match(messageToolSummary, /class="tool-file-list"/)
  assert.match(messageToolSummary, /status-succeeded/)
  assert.match(messageToolSummary, /status-failed/)
})

test('agent status bar does not keep a completed run visually stuck on screen', () => {
  assert.match(agentStatusBar, /const visible = ref\(false\)/)
  assert.match(agentStatusBar, /phase === 'done'/)
  assert.match(agentStatusBar, /setTimeout\(\(\) => \{ visible\.value = false \}/)
  assert.match(agentStatusBar, /v-if="visible"/)
})

test('OpenCode streaming is event-driven instead of waiting for prompt completion', () => {
  assert.match(useChat, /subscribeOpenCodeEvents/)
  assert.match(useChat, /fireOpenCodePrompt/)
  assert.match(useChat, /buildOpenCodePromptParts/)
  assert.match(useChat, /parts:\s*buildOpenCodePromptParts\(\{/)
  assert.match(useChat, /type === 'message\.part\.delta'/)
  assert.match(useChat, /const field = String\(properties\.field \|\| 'text'\)/)
  assert.match(useChat, /applyOpenCodePartDelta\(targetMsg, partId, field, delta\)/)
  assert.match(useChat, /applyTextPartToMessage/)
  assert.match(useChat, /applyReasoningPartToMessage/)
  assert.match(useChat, /scheduleFinalizeOpenCodeRun\('done'\)/)
  assert.match(useChat, /finalSyncError/)
  assert.doesNotMatch(useChat, /setPhase\('error', finalSyncError\)/)
  assert.match(useChat, /onClose:\s*\(\) => \{/)
  assert.match(useChat, /getOpenCodeSessionStatus\(client,\s*\{\s*directory:\s*effectiveDir\s*\}\)/)
  assert.match(useChat, /statusMap\?\.\[activeOpenCodeSessionId\]\?\.type === 'idle'/)
  assert.doesNotMatch(useChat, /onClose:\s*\(\) => \{[\s\S]{0,180}scheduleFinalizeOpenCodeRun\('done', 'event stream closed'\)/)
  assert.doesNotMatch(useChat, /await sendOpenCodePrompt/)
})

test('Web chat falls back to cloud completions without starting the desktop OpenCode kernel', () => {
  assert.match(useChat, /import \{ isTauriRuntime \} from '@\/utils\/tauriEnv'/)
  assert.match(useChat, /async function sendWebCloudMessage/)
  assert.match(useChat, /resolveApiConfig\(\{[\s\S]*forceCloud:\s*true/)
  assert.match(useChat, /\/v1\/chat\/completions/)
  assert.match(useChat, /if \(!isTauriRuntime\(\)\) \{[\s\S]*await sendWebCloudMessage\(options, runId, controller\)[\s\S]*return/)
  assert.match(useChat, /Web 云端对话失败/)
})

test('Web Skill mode reads built-in SKILL.md files instead of injecting OpenCode tool instructions', () => {
  assert.match(chatPanel, /const webBuiltInSkills = computed<OpenCodeSkillOption\[\]>/)
  assert.match(chatPanel, /agentStore\.getPresetSkills\(\)/)
  assert.match(chatPanel, /openCodeSkills\.value = webBuiltInSkills\.value/)
  assert.match(chatPanel, /:web-mode="!isTauriRuntime\(\)"/)
  assert.match(skillPickerBar, /dist\/skills 已随站点上传/)
  assert.match(useChat, /async function resolveSkillUriContent/)
  assert.match(useChat, /fetch\(`\/skills\/\$\{relativePath\}`\)/)
  assert.match(useChat, /await resolveWebSkillSystemPrompt\(skillName, agentStore\)/)
  assert.doesNotMatch(useChat, /const systemPrompt = \[[\s\S]{0,160}buildFixedSkillSystemInstruction\(skillName\)/)
})

test('long output continuation is visually grouped instead of shown as separate chat turns', () => {
  assert.match(useChat, /continuationParentId\?: string/)
  assert.match(useChat, /_continuationParentId\?: string/)
  assert.match(useChat, /continuationParentId:\s*options\._continuationParentId/)
  assert.match(useChat, /isContinuationPrompt\?: boolean/)
  assert.match(useChat, /_isContinuationPrompt\?: boolean/)
  assert.match(useChat, /isContinuationPrompt:\s*options\._isContinuationPrompt/)
  assert.match(chatPanel, /_continuationParentId:\s*messageId/)
  assert.match(chatPanel, /_isContinuationPrompt:\s*true/)
  assert.match(chatPanel, /continuationChildrenByParent/)
  assert.match(chatPanel, /:continuation-parts="continuationChildrenByParent\.get\(msg\.id\)"/)
  assert.match(chatPanel, /getContinuationTailMessage/)
  assert.match(chatPanel, /collectContinuationThreadIds/)
  assert.match(messageBubble, /ContinuationPart\[\]/)
  assert.match(messageBubble, /:finish-reason="part\.finishReason"/)
  assert.match(messageBubble, /class="msg-continuation-group"/)
})

test('message display owns base bubble styling instead of relying on parent scoped css', () => {
  assert.match(messageBubble, /\.msg-bubble\s*\{[\s\S]*max-width:\s*85%;/)
  assert.match(messageBubble, /\.msg\.user\s+\.msg-bubble\s*\{[\s\S]*background:/)
  assert.match(messageBubble, /\.msg\.assistant\s+\.msg-bubble\s*\{[\s\S]*background:/)
})

test('references open through safe external navigation instead of raw target blank links', () => {
  assert.match(messageReferences, /openExternal/)
  assert.match(messageReferences, /safeSearchResults/)
  assert.match(messageReferences, /isSafeSearchReferenceUrl/)
  assert.doesNotMatch(messageReferences, /target="_blank"/)
})

test('tool summary receives running state and latest tool result evidence', () => {
  assert.match(messageBubble, /isToolRunning/)
  assert.match(messageBubble, /latestToolResult/)
  assert.match(messageBubble, /:is-running="isToolRunning"/)
  assert.match(messageBubble, /!hasOpenCodeNonTextParts && \(\(toolCalls && toolCalls\.length\) \|\| officeDownloadFiles\.length \|\| latestToolResult\)/)
  assert.match(messageBubble, /:tool-result="latestToolResult"/)
  assert.match(chatPanel, /buildLatestToolResultByAssistantId/)
  assert.match(chatPanel, /latestToolResultByAssistantId\.get\(message\.id\)/)
  assert.doesNotMatch(chatPanel, /pendingToolResults/)
})

test('phase 0 guard keeps streaming rendering separate from final markdown rendering', () => {
  assert.match(messageBubble, /isStreamingMessage/)
  assert.match(messageBubble, /renderStreamingText/)
  assert.match(messageBubble, /createProgressiveStreamSmoother/)
  assert.match(messageBubble, /visibleStreamingContent/)
  assert.match(messageBubble, /displayContent/)
  assert.match(messageBubble, /renderStreamingText\(displayContent\.value\)/)
  assert.match(messageBubble, /visibleOpenCodeTextByPartId/)
  assert.match(chatPanel, /:is-streaming-message="isAssistantStreamingMessage\(msg\)"/)
})

test('file tree refreshes through the compact three-tab loader', () => {
  assert.match(fileTreePanel, /async function loadTab\(\)/)
  assert.match(fileTreePanel, /if \(activeTab\.value === 'history'\)/)
  assert.match(fileTreePanel, /await fileStore\.loadByCategory\(activeTab\.value\)/)
  assert.match(fileTreePanel, /onEvent\('refresh-file-list'[\s\S]*void loadTab\(\)/)
  assert.match(fileTreePanel, /@click="loadTab"/)
})

test('message bubble coerces message content before trim-dependent UI checks', () => {
  assert.match(messageBubble, /const normalizedContent = computed\(\(\) => String\(props\.content \|\| ''\)\)/)
  assert.doesNotMatch(messageBubble, /props\.content\.trim\(\)/)
})

test('phase 0 guard keeps OpenCode runtime boundaries out of the conversation experience layer', () => {
  assert.match(useChat, /type === 'session\.next\.agent\.switched'/)
  assert.match(useChat, /setPhase\('thinking', `Agent: \$\{properties\.agent \|\| 'OpenCode'\}`\)/)
  assert.match(useChat, /type === 'session\.next\.compaction\.started'/)
  assert.match(useChat, /setPhase\('thinking', 'OpenCode 正在压缩上下文'\)/)
  assert.doesNotMatch(useChat, /targetMsg\.content \+= `\\n\\n\\[系统事件\\]/)
  assert.match(chatPanel, /if \(m\.role === 'system'\) return false/)
  assert.match(chatPanel, /if \(m\.role === 'tool'\) return false/)
})

test('ChatPanel maps OpenCode P0 commands to native UI actions instead of invalid server slash commands', () => {
  assert.match(chatPanel, /command === 'model'[\s\S]*showModelMenu\.value = true/)
  assert.doesNotMatch(chatPanel, /command === 'agent'[\s\S]*showModelMenu\.value = true/)
  assert.match(chatPanel, /const sessionActionBySlash: Partial<Record<string, OpenCodeSessionAction>>/)
  assert.match(chatPanel, /summarize:\s*'compact'/)
  assert.match(chatPanel, /delete:\s*'delete'/)
  assert.doesNotMatch(chatPanel, /async function runSessionMenuCommand\(command: string\)/)
  assert.doesNotMatch(chatPanel, /@click="runSessionMenuCommand\('compact'\)"/)
  assert.doesNotMatch(chatPanel, />压缩上下文</)
  assert.doesNotMatch(chatPanel, /compactCurrentOpenCodeContext/)
  assert.doesNotMatch(chatPanel, /cp-clear-context-btn/)
  assert.doesNotMatch(chatPanel, /cp-session-command-menu/)
  assert.doesNotMatch(chatPanel, /OpenCode 官方会话命令/)
  assert.doesNotMatch(composerCommandSource, /command:\s*'compact'/)
  assert.doesNotMatch(composerCommandSource, /label:\s*'压缩上下文'/)
  assert.match(chatPanel, /const hiddenComposerSessionCommands = new Set\(\['compact', 'summarize'\]\)/)
  assert.match(chatPanel, /!hiddenComposerSessionCommands\.has\(item\.slash\)/)
  assert.match(chatPanel, /function startNew\(\) \{[\s\S]*await flushCurrentSessionPersist\(\)[\s\S]*await runSessionAction\('new'\)/)
  assert.doesNotMatch(chatPanel, /Web 工具/)
  assert.doesNotMatch(chatPanel, /openCodeTools: currentOpenCodeToolOverrides\(\)/)
  assert.doesNotMatch(chatPanel, /jcWebSearchEnabled/)
  assert.doesNotMatch(toolConnectionAdapter, /isWebSearchEnabled/)
  assert.doesNotMatch(toolConnectionAdapter, /jcWebSearchEnabled/)
  assert.doesNotMatch(toolConnectionAdapter, /webSearchEnabled/)
  assert.doesNotMatch(chatPanel, /清除上下文：/)
  assert.doesNotMatch(chatPanel, />上下文已清除</)
  assert.doesNotMatch(useChat, /\[上下文已清除\]/)
  assert.doesNotMatch(useChat, /clearContextBoundary/)
})

test('manual compact waits for official OpenCode context sync before claiming completion', () => {
  assert.match(useChat, /await compactOpenCodeSession\(client/)
  assert.match(useChat, /await waitOpenCodeSessionIdle\(client,\s*\{ sessionID,\s*directory:\s*effectiveDir \}\)/)
  assert.match(useChat, /waitForOpenCodeCompactionSync\(client,\s*sessionID,\s*beforeUsage\)/)
  assert.match(useChat, /invalidateOpenCodeSessionContextUsage\(sessionID\)/)
  assert.match(useChat, /latestUsage\.messageCount < beforeUsage\.messageCount \|\| latestUsage\.total < beforeUsage\.total/)
  assert.doesNotMatch(useChat, /countOpenCodeCompactionMessages\(latestMessages\)/)
  assert.doesNotMatch(useChat, /\| 'summarize'/)
  assert.doesNotMatch(useChat, /summarizeOpenCodeSession/)
  assert.match(useChat, /notifyOpenCodeRun\('OpenCode 压缩上下文等待同步'/)
  assert.match(useChat, /OpenCode 上下文已压缩/)
  assert.match(useChat, /已发起 OpenCode 上下文压缩，等待官方上下文同步/)
  assert.doesNotMatch(useChat, /已请求 OpenCode 压缩上下文/)
})

test('OpenCode session actions keep local session state aligned without header command menu', () => {
  assert.match(chatPanel, /async function flushCurrentSessionPersist\(\)/)
  assert.match(chatPanel, /const canCompactContext = computed\(\(\) =>[\s\S]*Boolean\(activeOpenCodeSessionId\.value\)[\s\S]*messages\.value\.some\(message => message\.role !== 'system'\)/)
  assert.match(chatPanel, /if \(action === 'compact' && !canCompactContext\.value\) \{[\s\S]*setLocalCommandNotice\('当前没有可压缩的 OpenCode 上下文，或会话仍在执行\/加载中。'\)[\s\S]*showComposerCommandMenu\.value = false[\s\S]*return/)
  assert.match(chatPanel, /if \(action === 'new' \|\| action === 'fork'\) \{[\s\S]*await flushCurrentSessionPersist\(\)/)
  assert.match(chatPanel, /const result = await runOpenCodeSessionAction\(action, currentOpenCodeCommandOptions\(\)\)/)
  assert.match(chatPanel, /if \(!result\.ok\) \{[\s\S]*showComposerCommandMenu\.value = false[\s\S]*return[\s\S]*\}/)
  assert.doesNotMatch(chatPanel, /showSessionCommandMenu/)
  assert.match(chatPanel, /action === 'fork' && result\.forkedSessionID/)
  assert.match(chatPanel, /currentSessionId = sessionStore\.startNewSession/)
  assert.match(chatPanel, /await persistCurrentSession\(\)/)
  assert.match(chatPanel, /if \(previousSessionId\) await sessionStore\.deleteSession\(previousSessionId\)/)
  assert.match(useChat, /setActiveOpenCodeSessionId\(forkedSessionID\)/)
  assert.match(useChat, /deletedSessionID: sessionID/)
})

test('OpenCode P4 notifications cover session actions slash commands and shell results', () => {
  assert.match(useChat, /function notifyOpenCodeRun/)
  assert.match(useChat, /function notifyOpenCodeSessionAction/)
  assert.match(useChat, /function notifyOpenCodeSlashCommand/)
  assert.match(useChat, /function notifyOpenCodeShellCommand/)
  assert.match(useChat, /notifyOpenCodeSessionAction\(action, true, sessionCommandNotice\.value\)/)
  assert.match(useChat, /notifyOpenCodeSessionAction\(action, false, detail\)/)
  assert.match(useChat, /notifyOpenCodeSlashCommand\(command, true\)/)
  assert.match(useChat, /notifyOpenCodeSlashCommand\(command, false, detail\)/)
  assert.match(useChat, /notifyOpenCodeShellCommand\(true\)/)
  assert.match(useChat, /notifyOpenCodeShellCommand\(false\)/)
  assert.match(useChat, /OpenCode Shell 已完成/)
  assert.match(useChat, /Shell 命令执行失败/)
  assert.doesNotMatch(useChat, /notifyOpenCodeShellCommand\(true, raw\)/)
  assert.doesNotMatch(useChat, /notifyOpenCodeShellCommand\(false, detail\)/)
  assert.doesNotMatch(useChat, /notifyOpenCodeRun\('OpenCode Shell 已完成', raw\)/)
})

test('OpenCode undo rejects local generated ids before calling official revert', () => {
  assert.match(useChat, /function isLocalGeneratedMessageId\(id: string\)/)
  assert.match(useChat, /await latestOpenCodeUserMessageId\(client\)/)
  assert.match(useChat, /!isLocalGeneratedMessageId\(message\.id\)/)
  assert.match(useChat, /没有可撤销的 OpenCode 用户消息/)
})

test('OpenCode Skill auto mode does not inherit legacy agentStore skill as a fixed Skill', () => {
  assert.match(chatPanel, /const selectedOpenCodeSkillOption = computed\(\(\) => \{/)
  assert.match(chatPanel, /selectableOpenCodeSkills\.value\.find\(skill => skill\.name === selectedName\) \|\| null/)
  assert.match(chatPanel, /const effectiveOpenCodeSkillName = computed\(\(\) =>\s*selectedOpenCodeSkillOption\.value\?\.name \|\| ''\s*\)/)
  assert.match(chatPanel, /useSkillsManageStore/)
  assert.match(chatPanel, /const centralOpenCodeSkills = computed<OpenCodeSkillOption\[\]>/)
  assert.match(chatPanel, /skillsManageStore\.centralSkills\.map/)
  assert.match(chatPanel, /skillsManageStore\.getSkillDisplayName\(skill\)/)
  assert.match(chatPanel, /const selectableOpenCodeSkills = computed<OpenCodeSkillOption\[\]>/)
  assert.match(chatPanel, /:skills="selectableOpenCodeSkills"/)
  assert.match(chatPanel, /skillsManageStore\.loadCentralSkills\(\{ scan: true \}\)/)
  assert.match(chatPanel, /openCodeSkills\.value = \[\]/)
  assert.doesNotMatch(chatPanel, /if \(isTauriRuntime\(\)\) void skillsManageStore\.loadCentralSkills\(\{ scan: true \}\)\.catch/)
  assert.match(skillPickerBar, /\(skill\.label \|\| ''\)\.toLowerCase\(\)\.includes\(q\)/)
  assert.match(chatPanel, /agentName: isMember\.value \? \(skillName \|\| agentStore\.modelLabel\) : agentStore\.modelLabel/)
  assert.match(chatPanel, /skillName: isMember\.value \? skillName \|\| undefined : undefined/)
  assert.doesNotMatch(chatPanel, /selectedOpenCodeSkill\.value \|\| \(isMember\.value \? agentStore\.currentAgent\?\.name/)
  assert.doesNotMatch(chatPanel, /当前Skill「/)
  assert.doesNotMatch(chatPanel, /const legacyAgentId = selectedOpenCodeSkill\.value \? undefined : agentStore\.currentAgent\?\.id/)
  assert.doesNotMatch(chatPanel, /agentStore\.restoreLastAgent\(\)/)
  assert.doesNotMatch(chatPanel, /agentId: isMember\.value \? agentStore\.currentAgent\?\.id/)
  assert.doesNotMatch(chatPanel, /const sessionSkill = session\?\.agentId/)
  assert.doesNotMatch(chatPanel, /agentStore\.currentAgent = sessionSkill/)
  assert.doesNotMatch(chatPanel, /agentStore\.currentAgent\?\.skillContent/)
})

test('smart auto-scroll is scheduled through requestAnimationFrame and exposed to ChatPanel', () => {
  assert.match(chatScrollNav, /function scheduleAutoScrollIfNeeded\(\)/)
  assert.match(chatScrollNav, /requestAnimationFrame/)
  assert.match(chatScrollNav, /isNearBottom\(el\)/)
  assert.match(chatScrollNav, /shouldAutoScrollAfterContentChange/)
  assert.match(chatScrollNav, /programmaticScrollTimer/)
  assert.match(chatScrollNav, /1500/)
  assert.match(chatScrollNav, /props\.isStreaming \? !userScrolled\.value : wasAtBottom/)
  assert.match(chatScrollNav, /function startStickyFollow\(\)/)
  assert.match(chatScrollNav, /MutationObserver/)
  assert.match(chatScrollNav, /ResizeObserver/)
  assert.match(chatScrollNav, /observeMessageElements/)
  assert.match(chatScrollNav, /if \(props\.isStreaming\) scheduleAutoScrollIfNeeded\(\)/)
  assert.match(chatScrollNav, /defineExpose\(\{ autoScrollIfNeeded, scheduleAutoScrollIfNeeded, startStickyFollow/)
  assert.match(chatPanel, /scrollNav\.value\?\.scheduleAutoScrollIfNeeded\(\)/)
  assert.match(chatPanel, /scrollNav\.value\?\.startStickyFollow\(\)/)
  assert.doesNotMatch(chatPanel, /scrollNav\.value\?\.autoScrollIfNeeded\(\)/)
})

test('floating message navigation does not block selecting the native message scrollbar', () => {
  assert.match(chatScrollNav, /\.scroll-nav-rail\s*\{[\s\S]*pointer-events:\s*none;/)
  assert.match(chatScrollNav, /\.scroll-btn\s*\{[\s\S]*pointer-events:\s*auto;/)
  assert.match(chatScrollNav, /right:\s*44px;/)
  assert.doesNotMatch(chatScrollNav, /right:\s*4px;/)
})

test('tool summaries and composer expose terminal states without looking stuck', () => {
  assert.match(messageToolSummary, /status-cancelled/)
  assert.match(messageToolSummary, /model\.status === 'cancelled'/)
  assert.match(chatPanel, /aria-label="停止生成"/)
  assert.match(chatPanel, /aria-label="发送消息"/)
  assert.match(chatPanel, /:aria-busy="isStreaming"/)
})

test('OpenCode session status and abort use official visible phases', () => {
  assert.match(useChat, /\|\s*'cancelling'/)
  assert.match(agentStatusBar, /phase === 'cancelling'/)
  assert.match(agentStatusBar, /label:\s*'停止中\.\.\.'/)
  assert.match(useChat, /status === 'busy'/)
  assert.match(useChat, /status === 'retry'/)
  assert.match(useChat, /OpenCode 正在停止/)
  assert.match(useChat, /云端请求正在停止/)
  assert.match(useChat, /isStreaming\.value = false[\s\S]*abortController\.value = null[\s\S]*currentToolProgress\.value = null[\s\S]*if \(finishReason === 'error'\)/)
  assert.match(useChat, /finishReason === 'abort'[\s\S]*setPhase\('idle'\)/)
  assert.doesNotMatch(useChat, /catch\s*\{\s*\}\s*\)\(\)/)
  assert.match(useChat, /OpenCode 停止失败/)
})

test('OpenCode official parts have first-class UI carriers', () => {
  assert.match(timelineRows, /export type OpenCodeTimelineRow/)
  assert.match(timelineRows, /normalizeOpenCodePart/)
  assert.match(timelineRows, /buildOpenCodeTimelineRows/)
  assert.match(timelineRows, /CONTEXT_GROUP_TOOLS/)
  assert.match(messageBubble, /OpenCodePartList/)
  assert.match(messageBubble, /openCodeTextParts/)
  assert.match(messageBubble, /openCodeReasoningContent/)
  assert.match(messageBubble, /renderOpenCodeTextPart/)
  assert.match(chatPanel, /:open-code-parts="msg\.openCodeParts"/)
  assert.match(openCodePartList, /part\.type === 'text' \|\| part\.type === 'reasoning'/)
  assert.match(openCodePartList, /part\.type === 'tool'/)
  assert.match(openCodePartList, /part\.type === 'file'/)
  assert.match(openCodePartList, /part\.type === 'patch' \|\| part\.type === 'diff'/)
  assert.match(openCodePartList, /part\.type === 'error'/)
})

test('OpenCode structured parts make messages visible without polluting markdown body', () => {
  assert.match(chatPanel, /m\.openCodeParts && m\.openCodeParts\.some/)
  assert.match(messageBubble, /hasMarkdownBody/)
  assert.match(messageBubble, /v-else-if="hasMarkdownBody/)
  assert.doesNotMatch(messageBubble, /v-else-if="!\(role === 'tool' && officeDownloadFiles\.length\)"/)
})

test('ChatPanel renders OpenCode assistant messages through timeline rows', () => {
  assert.match(chatPanel, /buildOpenCodeTimelineRows/)
  assert.match(chatPanel, /function openCodeRowsForMessage/)
  assert.match(chatPanel, /row\.type === 'assistant-part'/)
  assert.match(chatPanel, /:open-code-parts="\[row\.part\]"/)
  assert.match(chatPanel, /row\.type === 'system-event'/)
  assert.match(chatPanel, /cp-opencode-system/)
  assert.match(chatPanel, /row\.type === 'thinking'/)
  assert.match(chatPanel, /row\.type === 'error'/)
})

test('OpenCode runtime events are preserved as timeline system parts', () => {
  assert.match(timelineRows, /type:\s*'system-event'/)
  assert.match(timelineRows, /isSystemOpenCodePart/)
  assert.match(useChat, /type:\s*'agent'/)
  assert.match(useChat, /type:\s*'compaction'/)
  assert.match(useChat, /type:\s*'retry'/)
  assert.match(useChat, /type:\s*'step-finish'/)
  assert.match(useChat, /type:\s*'step-fail'/)
})

test('local chat sessions persist and restore linked OpenCode session ids', () => {
  const sessionStoreSource = readFileSync('src/stores/sessionStore.ts', 'utf8')
  assert.match(sessionStoreSource, /openCodeSessionId\?: string/)
  assert.match(sessionStoreSource, /options\?:\s*\{\s*openCodeSessionId\?: string\s*\}/)
  assert.match(sessionStoreSource, /openCodeSessionId:\s*options\?\.openCodeSessionId \|\| existingRecord\?\.openCodeSessionId/)
  assert.match(useChat, /getActiveOpenCodeSessionId/)
  assert.match(useChat, /activeOpenCodeSessionId:\s*readonly\(activeOpenCodeSessionIdRef\)/)
  assert.match(useChat, /openCodeSessionId\?: string/)
  assert.match(useChat, /setActiveOpenCodeSessionId\(String\(_baseline\?\.openCodeSessionId \|\| ''\)\)/)
  assert.match(chatPanel, /openCodeSessionId:\s*getActiveOpenCodeSessionId\(\)/)
})

test('session switching prefetches linked OpenCode sessions and uses cached official history', () => {
  assert.match(chatPanel, /prefetchOpenCodeSession/)
  assert.match(chatPanel, /listOpenCodeChatMessages/)
  assert.match(chatPanel, /session\?\.openCodeSessionId/)
  assert.match(chatPanel, /preferCache:\s*true/)
  assert.match(chatPanel, /openCodeHistory\.length \? openCodeHistory : history/)
})

test('OpenCode permission question and todo docks are mounted as official interaction carriers', () => {
  assert.match(interactiveBridge, /replyOpenCodePermission/)
  assert.match(interactiveBridge, /replyOpenCodeQuestion/)
  assert.match(interactiveBridge, /rejectOpenCodeQuestion/)
  assert.match(interactiveBridge, /listOpenCodeTodos/)
  assert.match(useChat, /type === 'permission\.asked' \|\| type === 'permission\.v2\.asked'/)
  assert.match(useChat, /type === 'question\.asked' \|\| type === 'question\.v2\.asked'/)
  assert.match(useChat, /type === 'todo\.updated'/)
  assert.match(chatPanel, /<PermissionDock :requests="pendingPermissions" @decide="respondPermission" \/>/)
  assert.match(chatPanel, /<QuestionDock :requests="pendingQuestions" @reply="replyQuestion" @reject="rejectQuestion" \/>/)
  assert.match(chatPanel, /<TodoDock :todos="sessionTodos" \/>/)
  assert.match(permissionDock, /once/)
  assert.match(permissionDock, /always/)
  assert.match(permissionDock, /reject/)
  assert.match(questionDock, /activeQuestion\.multiple/)
  assert.match(questionDock, /custom/)
  assert.match(todoDock, /in_progress/)
  assert.match(todoDock, /completed/)
})

test('OpenCode docks follow official above-composer ordering', () => {
  const order = [
    '<PermissionDock',
    '<QuestionDock',
    '<TodoDock',
    '<RevertDock',
    '<FollowupDock',
    '<SessionShareNotice',
    '<DiffReviewDock',
  ].map(token => chatPanel.indexOf(token))

  assert.ok(order.every(index => index >= 0), 'all official docks should be mounted in ChatPanel')
  assert.deepEqual([...order].sort((a, b) => a - b), order)
})

test('OpenCode context tools use a dedicated official-style grouped carrier', () => {
  assert.match(timelineRows, /type:\s*'context-group'/)
  assert.match(chatPanel, /row\.type === 'context-group'/)
  assert.match(openCodePartList, /context-group/)
  assert.match(openCodePartList, /opencode-context-group/)
  assert.match(openCodePartList, /contextSummary/)
})

test('OpenCode tool parts expose official default-open rules and error-card carrier', () => {
  assert.match(timelineRows, /openCodePartDefaultOpen/)
  assert.match(openCodePartList, /shellToolPartsExpanded/)
  assert.match(openCodePartList, /editToolPartsExpanded/)
  assert.match(openCodePartList, /opencode-tool-error-card/)
  assert.match(openCodePartList, /copyErrorDetail/)
  assert.match(openCodePartList, /part\.status === 'error'/)
})

test('OpenCode passive tools are not controlled by chat or warehouse switches', () => {
  assert.doesNotMatch(chatPanel, /<ToolPickerBar/)
  assert.doesNotMatch(chatPanel, /from '\.\/ToolPickerBar\.vue'/)
  assert.doesNotMatch(toolPickerBar, /toggleLocalTools/)
  assert.doesNotMatch(toolPickerBar, /localToolsEnabled/)
  assert.doesNotMatch(toolWarehousePanel, /toggleLocalTools/)
  assert.doesNotMatch(toolWarehousePanel, /localToolsEnabled/)
  assert.match(toolWarehousePanel, /OpenCode 被动工具由官方运行时管理/)
})

test('OpenCode slash and shell commands have visible official composer affordances', () => {
  assert.match(chatPanel, /openSlashCommandPalette/)
  assert.match(chatPanel, /openShellCommandPrompt/)
  assert.match(chatPanel, /aria-label="OpenCode 命令"/)
  assert.doesNotMatch(chatPanel, /title="OpenCode Shell" aria-label="OpenCode Shell"/)
  assert.match(chatPanel, /aria-label="OpenCode Shell 命令"/)
  assert.match(chatPanel, /高级命令/)
  assert.match(chatPanel, /高级命令 \/ Terminal/)
  assert.match(chatPanel, /runVisibleSlashText\(`\/\$\{command\}`/)
  assert.match(chatPanel, /runSlashCommand\(text, options\)/)
  assert.match(chatPanel, /runShellCommand\(command/)
})

test('OpenCode P4 terminal shell parts render as rich terminal output', () => {
  const shellDisplay = readFileSync('src/opencodeClient/shellDisplay.ts', 'utf8')
  assert.match(openCodePartList, /from '@\/opencodeClient\/shellDisplay'/)
  assert.match(openCodePartList, /const isShellPart = isOpenCodeShellPart/)
  assert.match(shellDisplay, /export function isOpenCodeShellPart/)
  assert.match(shellDisplay, /part\.type === 'shell'/)
  assert.match(shellDisplay, /toolName === 'bash' \|\| toolName === 'shell'/)
  assert.match(shellDisplay, /export function shellDisplayCommand/)
  assert.match(shellDisplay, /export function shellDisplayStdout/)
  assert.match(shellDisplay, /export function shellDisplayStderr/)
  assert.match(shellDisplay, /export function shellDisplayErrorText/)
  assert.match(shellDisplay, /export function shellDisplayExitLabel/)
  assert.match(shellDisplay, /export function shellDisplayDurationLabel/)
  assert.match(shellDisplay, /export function shellDisplayDetail/)
  assert.match(shellDisplay, /safeOpenCodeJsonSummary\(value, 3000\)/)
  assert.match(openCodePartList, /class="opencode-terminal"/)
  assert.match(openCodePartList, /class="opencode-terminal-command"/)
  assert.match(openCodePartList, />stdout</)
  assert.match(openCodePartList, />stderr</)
  assert.match(openCodePartList, /暂无 shell 输出/)
  assert.match(openCodePartList, /const shellDetail = shellDisplayDetail/)
  assert.match(openCodePartList, /isShellPart\(part\) \? shellDetail\(part\)/)
})

test('OpenCode P2 advanced commands are local UI carriers with source labels', () => {
  assert.match(openCodeCatalog, /listOpenCodeCommands/)
  assert.match(openCodeCatalog, /commandApi\.list/)
  assert.match(chatPanel, /listOpenCodeCommands/)
  assert.match(chatPanel, /openCodeCustomCommands/)
  assert.match(chatPanel, /refreshOpenCodeCommands/)
  assert.match(chatPanel, /label: 'MCP 外部工具'/)
  assert.match(chatPanel, /source: 'MCP'/)
  assert.match(chatPanel, /label: '打开项目文件'/)
  assert.match(chatPanel, /source: 'Custom file\.open'/)
  assert.match(chatPanel, /label: '添加选区上下文'/)
  assert.match(chatPanel, /source: 'Custom context\.addSelection'/)
  assert.match(chatPanel, /label: 'Terminal 面板'/)
  assert.match(chatPanel, /source: 'Local UI terminal\.toggle'/)
  assert.match(chatPanel, /label: '新建 Terminal'/)
  assert.match(chatPanel, /source: 'Local UI terminal\.new'/)
  assert.match(chatPanel, /label: 'Skill 命令'/)
  assert.match(chatPanel, /Skill \/ MCP \/ Custom/)
  assert.match(chatPanel, /cp-composer-command-error/)
  assert.match(chatPanel, /label: '归档'/)
  assert.match(chatPanel, /runLocalOpenCodeUiCommand\(command\)/)
  assert.match(chatPanel, /command === 'mcp'/)
  assert.match(chatPanel, /command === 'terminal' \|\| command === 'terminal\.toggle'/)
  assert.match(chatPanel, /command === 'open' \|\| command === 'file\.open'/)
  assert.match(chatPanel, /command === 'context' \|\| command === 'selection' \|\| command === 'context\.addselection'/)
  assert.ok(
    chatPanel.indexOf('if (runLocalOpenCodeUiCommand(command)) return') < chatPanel.indexOf('await runSlashCommand(text, options)'),
    'local P2 UI commands should be intercepted before server slash execution',
  )
})

test('OpenCode task tool renders as a Subtask child-session carrier', () => {
  assert.match(openCodePartList, /isSubtaskPart/)
  assert.match(openCodePartList, /part\.type === 'subtask'/)
  assert.match(openCodePartList, /part\.toolName === 'task'/)
  assert.match(openCodePartList, /Subtask \/ 子任务/)
  assert.match(openCodePartList, /打开子任务会话/)
  assert.match(openCodePartList, /subtaskSessionId/)
  assert.match(messageBubble, /@open-subtask="emit\('openSubtask', \$event\)"/)
  assert.match(chatPanel, /@open-subtask="openSubtaskSession"/)
  assert.match(chatPanel, /async function openSubtaskSession/)
  assert.match(chatPanel, /listOpenCodeChatMessages\([\s\S]*createJiucaiOpenCodeClient\(handle,\s*selectedProjectDir\.value \|\| undefined\)[\s\S]*sessionId[\s\S]*directory:\s*selectedProjectDir\.value \|\| handle\.directory/)
  assert.match(chatPanel, /sessionStore\.startNewSession/)
  assert.match(chatPanel, /openCodeSessionId: sessionId/)
  assert.doesNotMatch(chatPanel, /待 OpenCode session 路由接入/)
})

test('OpenCode project directory flows through server client session and tools', () => {
  assert.match(chatPanel, /ensureOpenCodeServer\(\{\s*config:\s*projectedConfig,\s*directory:\s*selectedProjectDir\.value \|\| undefined\s*\}\)/)
  assert.match(chatPanel, /listOpenCodeSkills\(createJiucaiOpenCodeClient\(handle,\s*selectedProjectDir\.value \|\| undefined\),\s*\{\s*directory:\s*selectedProjectDir\.value \|\| handle\.directory/)
  assert.match(chatPanel, /listOpenCodeCommands\(createJiucaiOpenCodeClient\(handle,\s*selectedProjectDir\.value \|\| undefined\),\s*\{\s*directory:\s*selectedProjectDir\.value \|\| handle\.directory/)
  assert.match(chatPanel, /listOpenCodeChatMessages\([\s\S]*createJiucaiOpenCodeClient\(handle,\s*selectedProjectDir\.value \|\| undefined\)[\s\S]*sessionId[\s\S]*directory:\s*selectedProjectDir\.value \|\| handle\.directory/)

  assert.match(useChat, /function resolveOpenCodeDirectory\(handle:[\s\S]*projectDir\?: string[\s\S]*\): string/)
  assert.match(useChat, /const projectDir = options\.openCodeProjectDir \|\| ''[\s\S]*ensureOpenCodeServer\(\{\s*config:\s*projectedConfig,\s*directory:\s*projectDir \|\| undefined\s*\}\)/)
  assert.match(useChat, /const effectiveDir = resolveOpenCodeDirectory\(handle,\s*projectDir\)/)
  assert.match(useChat, /activeOpenCodeDirectory = effectiveDir/)
  assert.match(useChat, /createOpenCodeSession\(client,\s*\{[\s\S]*directory:\s*effectiveDir/)
  assert.match(useChat, /fireOpenCodePrompt\(client,\s*\{[\s\S]*directory:\s*effectiveDir/)
  assert.match(useChat, /subscribeOpenCodeEvents\(client,[\s\S]*\{\s*directory:\s*effectiveDir/)
  assert.match(useChat, /const location = \{\s*directory:\s*effectiveDir\s*\}/)
  assert.doesNotMatch(useChat, /const handle = await ensureOpenCodeServer\(\{\s*config:\s*projectedConfig\s*\}\)/)
  assert.doesNotMatch(useChat, /const location = \{\s*directory:\s*handle\.directory\s*\}/)
  assert.doesNotMatch(useChat, /directory:\s*handle\.directory/)
})

test('OpenCode P2 model menu stays model-only without variant UI copy', () => {
  assert.doesNotMatch(chatPanel, /cp-model-variant-cycle/)
  assert.doesNotMatch(chatPanel, /cp-model-label">切换 Variant \/ 变体/)
  assert.doesNotMatch(chatPanel, /model\.variant\.cycle/)
  assert.doesNotMatch(chatPanel, /cycleModelVariant/)
  assert.doesNotMatch(chatPanel, /均衡/)
  assert.doesNotMatch(chatPanel, /快速/)
  assert.doesNotMatch(chatPanel, /深度/)
  assert.doesNotMatch(chatPanel, /能力说明/)
})

test('OpenCode local command notices do not mask server command notices indefinitely', () => {
  assert.match(chatPanel, /localCommandNoticeTimer/)
  assert.match(chatPanel, /clearLocalCommandNotice/)
  assert.match(chatPanel, /setTimeout\(\(\) => \{\n\s+localCommandNotice\.value = ''/)
  assert.match(chatPanel, /v-if="sessionCommandNotice" class="cp-session-notice"/)
  assert.match(chatPanel, /v-if="localCommandNotice" class="cp-session-notice local"/)
})

test('OpenCode permission and question docks await parent async handlers before re-enabling actions', () => {
  assert.match(permissionDock, /onDecide\?:/)
  assert.match(permissionDock, /await props\.onDecide/)
  assert.doesNotMatch(permissionDock, /await emit\('decide'/)
  assert.match(questionDock, /onReply\?:/)
  assert.match(questionDock, /onReject\?:/)
  assert.match(questionDock, /await props\.onReply/)
  assert.match(questionDock, /await props\.onReject/)
  assert.doesNotMatch(questionDock, /await emit\('reply'/)
})

test('OpenCode P3 low-priority commands are carried without adding permanent chrome', () => {
  assert.match(chatPanel, /shouldShowTabCloseCommand/)
  assert.match(chatPanel, /command: 'message\.previous'/)
  assert.match(chatPanel, /command: 'message\.next'/)
  assert.match(chatPanel, /command: 'tab\.close'/)
  assert.match(chatPanel, /command: 'fileTree\.toggle'/)
  assert.match(chatPanel, /item\.command !== 'tab\.close' \|\| shouldShowTabCloseCommand\(activeEditorFileId\.value\)/)
  assert.match(chatPanel, /command === 'message\.previous'/)
  assert.match(chatPanel, /command === 'message\.next'/)
  assert.match(chatPanel, /command === 'tab\.close'/)
  assert.match(chatPanel, /command === 'filetree\.toggle' \|\| command === 'filetree'/)
  assert.match(chatPanel, /command === 'input\.focus' \|\| command === 'focus'/)
  assert.doesNotMatch(chatPanel, /command === 'agent\.cycle\.reverse' \|\| command === 'agent\.reverse'/)
  assert.match(chatPanel, /scrollNav\.value\?\.scrollPrev\(\)/)
  assert.match(chatPanel, /scrollNav\.value\?\.scrollNext\(\)/)
  assert.match(chatPanel, /emitEvent\('toggle-file-tree'\)/)
  assert.match(chatPanel, /emitEvent\('editor-close-current-tab'/)
  assert.match(editorPanel, /closeEditorTabSafely/)
  assert.match(editorPanel, /onEvent\('editor-close-current-tab'/)
  assert.match(editorPanel, /const payloadFileId = payload\?\.fileId \? String\(payload\.fileId\) : null/)
  assert.match(editorPanel, /getCurrentFileId: \(\) => currentFileId\.value/)
  assert.match(editorPanel, /saveCurrentFile: async \(closingFileId\)/)
  assert.match(editorPanel, /await saveExistingEditorFile\(closingFileId, snapshot\)/)
  assert.match(editorPanel, /function buildCurrentEditorSaveSnapshot/)
  assert.match(editorPanel, /async function saveExistingEditorFile\(fileId: string, snapshot: EditorSaveSnapshot\)/)
  assert.match(editorPanel, /editor\.value\?\.commands\.clearContent\(\)/)
})

test('OpenCode P3 shortcuts follow official keybinds and avoid extra main buttons', () => {
  assert.match(chatPanel, /resolveOpenCodeP3KeyAction/)
  assert.match(chatPanel, /function onGlobalKeydown/)
  assert.match(chatPanel, /isTextInput,/)
  assert.match(chatPanel, /isTauriRuntime: isTauriRuntime\(\)/)
  assert.match(chatPanel, /hasActiveEditorFile: Boolean\(activeEditorFileId\.value\)/)
  assert.match(chatPanel, /action === 'focus-input'/)
  assert.match(chatPanel, /action === 'message-previous'/)
  assert.match(chatPanel, /action === 'message-next'/)
  assert.match(chatPanel, /action === 'toggle-file-tree'/)
  assert.match(chatPanel, /action === 'close-tab'/)
  assert.match(chatPanel, /window\.addEventListener\('keydown', onGlobalKeydown\)/)
  assert.match(chatPanel, /window\.removeEventListener\('keydown', onGlobalKeydown\)/)
  assert.doesNotMatch(chatPanel, /title="聚焦输入"/)
  assert.doesNotMatch(chatPanel, /agent\.cycle \/ agent\.cycle\.reverse 使用同一个 Agent 菜单承载/)
})

test('OpenCode share results use an actionable copy and open carrier', () => {
  assert.match(useChat, /sessionShareUrl/)
  assert.match(useChat, /sessionShareUrl\.value = shared\?\./)
  assert.match(chatPanel, /SessionShareNotice/)
  assert.match(chatPanel, /:url="sessionShareUrl"/)
  assert.match(sessionShareNotice, /copyShareUrl/)
  assert.match(sessionShareNotice, /openShareUrl/)
  assert.match(sessionShareNotice, /write_clipboard_text/)
  assert.match(sessionShareNotice, /openExternal/)
})

test('OpenCode P1 Revert and Followup docks are mounted above the composer', () => {
  assert.match(revertDock, /data-component="session-revert-dock"/)
  assert.match(revertDock, /Revert 可恢复项/)
  assert.match(revertDock, /恢复消息/)
  assert.match(followupDock, /data-component="session-followup-dock"/)
  assert.match(followupDock, /后续操作建议/)
  assert.match(followupDock, /发送建议/)
  assert.match(followupDock, /编辑后发送/)
  assert.match(chatPanel, /<RevertDock/)
  assert.match(chatPanel, /<FollowupDock/)
  assert.match(useChat, /sessionRevertItems/)
  assert.match(useChat, /sessionFollowups/)
  assert.match(useChat, /session\.followup/)
})

test('OpenCode redo and RevertDock follow official revert boundary semantics', () => {
  assert.match(useChat, /refreshRevertItemsAfterRestored/)
  assert.match(useChat, /restoreOpenCodeRevertBoundary/)
  assert.match(useChat, /nextUserMessageIdAfter/)
  assert.match(useChat, /const startIndex = users\.findIndex\(message => message\.id === revertMessageID\)/)
  assert.match(useChat, /const index = users\.findIndex\(message => message\.id === messageID\)/)
  assert.match(useChat, /await revertOpenCodeSessionMessage\(client, \{ \.\.\.location, messageID: nextMessageID \}\)/)
  assert.match(useChat, /await unrevertOpenCodeSession\(client, location\)/)
  assert.match(useChat, /await restoreOpenCodeRevertBoundary\(client,\s*\{ sessionID,\s*directory:\s*effectiveDir \}, itemId\)/)
  assert.doesNotMatch(useChat, /message\.id > restoreMessageID/)
  assert.doesNotMatch(useChat, /message\.id >= revertMessageID/)
})

test('OpenCode P1 permissions require explicit user decisions without hidden autoaccept state', () => {
  assert.match(useChat, /pendingPermissions\.value = upsertById\(pendingPermissions\.value, request\)/)
  assert.doesNotMatch(useChat, /permissionAutoAcceptEnabled/)
  assert.doesNotMatch(useChat, /jcOpenCodePermissionAutoAccept/)
  assert.doesNotMatch(useChat, /function readBooleanLocalStorage/)
  assert.doesNotMatch(useChat, /function updatePermissionAutoAccept/)
  assert.doesNotMatch(useChat, /function togglePermissionAutoAccept/)
  assert.doesNotMatch(useChat, /autoAcceptPermission/)
  assert.doesNotMatch(useChat, /自动批准权限/)
  assert.match(useChat, /OpenCode 权限回复失败/)
  assert.match(useChat, /pendingPermissions\.value = removeById\(pendingPermissions\.value, requestID\)/)
  assert.doesNotMatch(chatPanel, /自动批准权限：\{\{ permissionAutoAcceptEnabled \? '开' : '关' \}\}/)
})

test('OpenCode P1 diff summary stays wired without vault context carriers', () => {
  assert.match(diffReviewDock, /data-component="session-diff-summary"/)
  assert.match(diffReviewDock, /Review \/ Diff · \{\{ totals\.fileCount \}\} 个文件变更/)
  assert.doesNotMatch(chatPanel, /Vault 上下文：\{\{ activeVaultContextLabel \}\}/)
  assert.doesNotMatch(chatPanel, /openCodeContextUsage/)
  assert.doesNotMatch(chatPanel, /Token 水位/)
  assert.doesNotMatch(chatPanel, /buildSelectedVaultContextFiles/)
  assert.doesNotMatch(chatPanel, /buildOpenCodeVaultContextFiles/)
  assert.doesNotMatch(chatPanel, /syncOpenCodeVaultContext/)
  assert.doesNotMatch(chatPanel, /vaultContextSync/)
  assert.doesNotMatch(chatPanel, /vault-selected/)
  assert.doesNotMatch(chatPanel, /vault-cleared/)
  assert.doesNotMatch(useChat, /syncOpenCodeVaultContext/)
  assert.doesNotMatch(useChat, /buildOpenCodeVaultMountInstruction/)
  assert.doesNotMatch(useChat, /buildSelectedOpenCodeVaultInstruction/)
})

test('OpenCode P4 review diff panel exposes file and hunk level review carriers', () => {
  assert.match(diffReviewDock, /buildDiffReviewModel/)
  assert.match(diffReviewDock, /data-component="session-diff-review-panel"/)
  assert.match(diffReviewDock, /可审查文件 \{\{ totals\.hasPatchCount \}\}\/\{\{ totals\.fileCount \}\}/)
  assert.match(diffReviewDock, />只读</)
  assert.doesNotMatch(diffReviewDock, /接受|回滚|应用/)
  assert.match(diffReviewDock, /v-for="hunk in file\.hunks"/)
  assert.match(diffReviewDock, /class="diff-line"/)
  assert.match(diffReviewDock, /line-\$\{line\.kind\}/)
  assert.match(diffReviewDock, /lineNumber\(line\)/)
  assert.match(diffReviewDock, /当前 OpenCode diff 只返回文件摘要，没有返回 patch 详情/)
  assert.match(diffReviewSource, /export function buildDiffReviewModel/)
  assert.match(diffReviewSource, /parsePatchHunks/)
  assert.match(diffReviewSource, /DiffReviewLineKind = 'add' \| 'del' \| 'context' \| 'meta'/)
})

test('OpenCode session switching clears stale share and command notice UI state', () => {
  assert.match(
    useChat,
    /function loadMessages\(history: ChatMessage\[\], _baseline\?: RuntimeContextBaseline\)[\s\S]*sessionShareUrl\.value = ''[\s\S]*sessionCommandNotice\.value = ''[\s\S]*resetToolState\(\)/,
  )
})

test('OpenCode P1 model selector stays wired to the official catalog without extra model UI copy', () => {
  const modelButton = chatPanel.match(/<button class="cp-model-btn" @click="toggleModelMenu">[\s\S]*?<\/button>/)?.[0] || ''
  assert.doesNotMatch(chatPanel, /来源：OpenCode model\.list/)
  assert.match(modelButton, /\{\{ agentStore\.currentModel \}\}/)
  assert.doesNotMatch(modelButton, /\{\{ agentStore\.modelLabel \}\}/)
  assert.match(chatPanel, /OpenCode 官方模型列表未就绪/)
  assert.match(chatPanel, /v-for="m in agentStore\.openCodeTextModels"/)
  assert.match(chatPanel, /<span class="cp-model-label">\{\{ m\.id \}\}<\/span>/)
  assert.match(agentStoreSource, /listOpenCodeModels/)
  assert.match(agentStoreSource, /openCodeTextModels/)
  assert.match(agentStoreSource, /const modelLabel = computed\(\(\) => \{\s*return currentModel\.value\s*\}\)/)
  assert.doesNotMatch(agentStoreSource, /return f \? f\.label : currentModel\.value\.split/)
  assert.doesNotMatch(useChat, /agent: options\.openCodeAgent \|\| 'build'/)
})

test('OpenCode project workspace does not declare legacy vault mount fs scopes', () => {
  const permissions = tauriDefaultCapability.permissions as any[]
  assert.equal(JSON.stringify(permissions).includes('.jiucaihezi-vaults/current'), false)
})

test('OpenCode skill tool part has a first-class Skill loaded card', () => {
  assert.match(openCodePartList, /isSkillToolPart/)
  assert.match(openCodePartList, /skillToolName/)
  assert.match(openCodePartList, /已加载 Skill：/)
  assert.match(openCodePartList, /OpenCode 官方 skill tool 已返回 SKILL\.md 内容/)
  assert.match(openCodePartList, /Skill 加载失败，请检查名称、权限或扫描路径/)
})

test('Help center is the professional tutorial layer for OpenCode terms and risky controls', () => {
  assert.match(i18nIndex, /帮助 \/ 教程中心/)
  assert.match(i18nIndex, /OpenCode 工作台指南/)
  assert.match(workspaceLayout, /专业术语表/)
  assert.match(workspaceLayout, /UI 按钮说明/)
  assert.match(workspaceLayout, /常见任务教程/)
  assert.match(workspaceLayout, /使用场景索引/)
  assert.match(workspaceLayout, /权限与安全/)
  assert.match(workspaceLayout, /OpenCode 对齐说明/)
  assert.match(workspaceLayout, /\/model 在本地打开模型菜单/)
  assert.doesNotMatch(workspaceLayout, /Agent：/)
  assert.doesNotMatch(workspaceLayout, /模型、Agent、Skill/)
  assert.doesNotMatch(workspaceLayout, /Agent：来自 OpenCode agent\.list/)
  assert.doesNotMatch(workspaceLayout, /\/model、\/agent 不发送到服务端/)
  assert.doesNotMatch(workspaceLayout, /自动批准权限默认关闭/)
  assert.doesNotMatch(workspaceLayout, /诸葛亮/)
  assert.doesNotMatch(workspaceLayout, /司马懿/)
  assert.doesNotMatch(workspaceLayout, /周瑜/)
})
